version: '3'


volumes:
  reef:


services:
  reef:
    build: .
    image: "t2b/reefcon"
    ports:
     - "2000-2002:2000-2002"
    volumes:
     - "reef:/rdat"
    environment:
     - Reef_Key=Reef
     - Reef_Path=/rdat
    command: "tail -F anything"
